service:
  name: connectwiseworker

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  memorySize: 256
  runtime: nodejs14.x
  region: ap-southeast-2

functions:
  blacklistCC:
    handler: src/functions/tickets/blacklistCC.handle
    events:
      - http:
          path: /tickets/blacklistCC
          method: POST
          cors: true
